### ISSUE TITLE
invalid archive returned from 'https://dl.cloudsmith.io/QQ43WPa2Y7VlFUM3/proglove/markconnectiossdk-prod/raw/names/ConnectSDK-2.4.0.xcframework/versions/2.4.0/ConnectSDK-2.4.0.xcframework.zip?accept_eula=7' which is required by binary target 'ConnectSDK'

### ISSUE THREAD

**Issue by LuisMDeveloper** [workaroundgmbh/pg-connect-sdk-ios#18] opened 2024-06-18 20:54 UTC
error: 
invalid archive returned from 'https://dl.cloudsmith.io/QQ43WPa2Y7VlFUM3/proglove/markconnectiossdk-prod/raw/names/ConnectSDK-2.4.0.xcframework/versions/2.4.0/ConnectSDK-2.4.0.xcframework.zip?accept_eula=7' which is required by binary target 'ConnectSDK'
due EULA update (Last updated June 14, 2024 — Revision 8)

probable fix:
update this line
https://github.com/workaroundgmbh/pg-connect-sdk-ios/blob/8f7a05b8f3ecfed6bd887553203e7b9ab5efbd13/Package.swift#L22

**Comment by andriybashta** [comment] 2024-06-20 11:31
The same issue for me. Please fix

**Comment by eminemArun** [comment] 2024-06-21 09:38
Hi, Any update on the same issue?

**Comment by vlasty-proglove** [comment] 2024-06-25 07:33
Thank you for your feedback, our EULA got updated, and that probably created a different accept-eula confirmation number.
This will be fixed today.

**Comment by vlasty-proglove** [comment] 2024-06-25 07:57
We are gathering some info so we can improve our SDK, can I ask @andriybashta, @eminemArun, @diegoOCR  and @LuisMDeveloper if you can please tell me what is your minimum iOS build target?

Thank you.

**Comment by andriybashta** [comment] 2024-06-25 09:34
> can please tell me what is your minimum iOS build target
It's iOS 15.0 min for me, @vlasty-proglove

**Comment by eminemArun** [comment] 2024-06-25 10:19
> We are gathering some info so we can improve our SDK, can I ask @andriybashta, @eminemArun, @natemann @chris-jarvi and @LuisMDeveloper if you can please tell me what is your minimum iOS build target?
> 
> Thank you.


iOS 13 for me.

**Comment by vlasty-proglove** [comment] 2024-06-25 10:36
Thank you @eminemArun and @andriybashta 

As for this problem resolution:

Since the EULA revision has changed the link is probably broken for 2.3.0, not just 2.4.0.
I will create two new commits, both will have updated links.
The problem that you might come across is for 2.3.0 since I will need to move the tag on the newer commit.

If that happens, the resolution to the problem is just clearing the DerivedData, Package cache and trying to rebuild it.

I will notify here once the commits are merged.

**Comment by vlasty-proglove** [comment] 2024-06-25 11:17
Hi all, the problem has been resolved with the 2.3.0 and 2.4.0 versions.

Here are the steps for you to make it work without additional hassle.

1. Close Xcode and all of the projects
2. Clear Derived Data
3. Clear the SPM cache by using the terminal commands in the accepted answer from stackoverflow
https://stackoverflow.com/questions/72788019/where-is-swift-package-manager-cache-located-swift-5-7
4. Open the project and if the error persists, Packages > Reset Package Cache, and Packages > Update to latest Package Versions

My suggestion is to use UpToNextMinor for the rule of the package.

Thank you for your patience, and please let me know if this resolves the problem.

**Comment by eminemArun** [comment] 2024-06-28 13:19
@vlasty-proglove  Thanks for the update.

**Comment by eminemArun** [comment] 2024-06-28 13:26
@vlasty-proglove  Also I wonder if you can suggest how to deallocate the PGCentralManager object from memory.

   ```
 var central: PGCentralManager!
        self.central = nil // Will it work?
```

**Comment by vlasty-proglove** [comment] 2024-06-28 13:47
> @vlasty-proglove Also I wonder if you can suggest how to deallocate the PGCentralManager object from memory.
> 
> ```
> var central: PGCentralManager!
>      self.central = nil // Will it work?
> ```

That code is from the example app, correct?
Since initial ViewController lives as long as the application is alive, the code that you suggested will work, because the PGCentralManager gets initialized in the viewDidLoad before even accessing again any of the features.

The reason you might want to deallocate it is if you don't need PGCentralManager in some cases during the running of your app, in which case, you can set your central as optional just to be sure that you are not accessing it somewhere where it needs to exist and you set it to nil.

**Closed** 2024-07-02 06:53 UTC
